# Generated by Django 4.2.4 on 2024-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_descrip_libro_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantactame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
